name = "Saxophone"
uuid = "cf5d2b88-b27d-487e-b2d1-e1d939812bcb"
authors = ["Fabian Byléhn <f.bylehn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
